_target_: rgbd_dataset.rgbd_dataset.datasets.HM3D.HM3D
dataset_name: "hm3d"
base_path: ???
scene: "00824"
width: 1080
height: 720
fx: 540.0
fy: 540.0
cx: 540.0
cy: 360.0
resized_width: -1
resized_height: -1
sequence_start: 0
sequence_end: -1
sequence_stride: 20
relative_pose: False
depth_scale: 1000.0
point_cloud: False
depth_trunc: 8.0
